# Generated by Django 2.2.2 on 2019-06-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_kpi', models.CharField(max_length=200)),
                ('meta_kpi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Info_kpi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_kpi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_kpi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=200)),
                ('id_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.Indicador')),
                ('id_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.Info_kpi')),
            ],
        ),
    ]
