# Generated by Django 2.2.2 on 2019-06-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_kpi',
            name='fecha_modificacion',
            field=models.CharField(default=435, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info_kpi',
            name='id_indicador',
            field=models.ManyToManyField(blank=True, to='indicador.Indicador'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='info_kpi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Detalle_kpi',
        ),
    ]
