# Generated by Django 2.2.2 on 2019-06-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0002_auto_20190629_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='categoria',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
