# Generated by Django 2.2.2 on 2019-06-30 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0003_indicador_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='categoria',
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.Indicador')),
            ],
        ),
    ]
