# Generated by Django 2.2.2 on 2019-06-30 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0005_auto_20190629_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.Categoria'),
        ),
    ]
