# Generated by Django 2.2.2 on 2019-06-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0006_auto_20190629_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_kpi',
            name='id_indicador',
        ),
        migrations.AddField(
            model_name='indicador',
            name='info',
            field=models.ManyToManyField(blank=True, null=True, to='indicador.Info_kpi'),
        ),
    ]
