# Generated by Django 2.2.2 on 2019-07-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0007_auto_20190630_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='info',
        ),
        migrations.AddField(
            model_name='info_kpi',
            name='indicador',
            field=models.ManyToManyField(blank=True, null=True, to='indicador.Indicador'),
        ),
    ]
