# Generated by Django 2.2.2 on 2019-07-01 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0008_auto_20190630_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_kpi',
            name='indicador',
        ),
        migrations.AddField(
            model_name='info_kpi',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.Indicador'),
        ),
    ]
