# Generated by Django 2.2.2 on 2019-07-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0009_auto_20190630_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_kpi',
            name='fecha_modificacion',
            field=models.DateField(),
        ),
    ]
