# Generated by Django 2.2.2 on 2019-07-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0010_auto_20190701_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_kpi',
            name='fecha_modificacion',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
    ]
