# Generated by Django 2.2.2 on 2019-06-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tablero', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kpi_tablero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicador.Indicador')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.Tablero')),
            ],
        ),
    ]
