# Generated by Django 2.2.2 on 2019-06-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0001_initial'),
        ('tablero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='indicador',
            field=models.ManyToManyField(blank=True, to='indicador.Indicador'),
        ),
    ]
