# Generated by Django 2.2.2 on 2019-06-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0003_remove_tablero_indicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi_tablero',
            name='tablero',
        ),
        migrations.AddField(
            model_name='kpi_tablero',
            name='tablero',
            field=models.ManyToManyField(blank=True, to='tablero.Tablero'),
        ),
    ]
