# Generated by Django 2.2.2 on 2019-06-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0006_auto_20190629_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi_tablero',
            name='tablero',
            field=models.ManyToManyField(to='tablero.Tablero'),
        ),
    ]
