# Generated by Django 2.2.2 on 2019-06-29 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0001_initial'),
        ('tablero', '0007_auto_20190629_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi_tablero',
            name='indicador',
        ),
        migrations.AddField(
            model_name='kpi_tablero',
            name='indicador',
            field=models.ManyToManyField(blank=True, to='indicador.Indicador'),
        ),
        migrations.RemoveField(
            model_name='kpi_tablero',
            name='tablero',
        ),
        migrations.AddField(
            model_name='kpi_tablero',
            name='tablero',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='tablero.Tablero'),
            preserve_default=False,
        ),
    ]
