# Generated by Django 2.2.2 on 2019-06-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0009_auto_20190629_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Kpi_tablero',
        ),
    ]
